import { Issue, AppUser, CategoryRule, AuditLog, SoundSettings, GeneralSettings, CabBusinessActivity } from '../types';
import { calculateDueDate } from './sla';
import { getDefaultPermissionsForRole } from './permissions';

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'usr-1',
    name: 'أحمد العتيبي',
    username: 'admin',
    email: 'admin@company.com',
    role: 'Admin',
    department: 'الإدارة العليا / IT Operations',
    avatar: 'أ',
    password: 'admin',
    permissions: getDefaultPermissionsForRole('Admin'),
  },
  {
    id: 'usr-2',
    name: 'محمد علي',
    username: 'agent1',
    email: 'agent1@company.com',
    role: 'Agent',
    department: 'فريق الدعم البرمجي',
    avatar: 'م',
    password: '123',
    permissions: getDefaultPermissionsForRole('Agent'),
  },
  {
    id: 'usr-3',
    name: 'سارة خالد',
    username: 'agent2',
    email: 'sara@company.com',
    role: 'Supervisor',
    department: 'خدمة العملاء واللوجستيات',
    avatar: 'س',
    password: '123',
    permissions: getDefaultPermissionsForRole('Supervisor'),
  },
  {
    id: 'usr-4',
    name: 'عمر اليافعي',
    username: 'agent3',
    email: 'omar@company.com',
    role: 'Agent',
    department: 'البنية التحتية والشبكات',
    avatar: 'ع',
    password: '123',
    permissions: getDefaultPermissionsForRole('Agent'),
  },
  {
    id: 'usr-1790256968066',
    name: 'محمد رمضان',
    username: 'محمد.رمضان',
    email: 'محمد.رمضان@support.internal',
    role: 'Supervisor',
    department: 'بيب',
    avatar: 'م',
    password: '123',
    permissions: getDefaultPermissionsForRole('Supervisor'),
  },
  {
    id: 'usr-1790553494732',
    name: 'سسب',
    username: 'يسي',
    email: 'jsf@gmail.com',
    role: 'Agent',
    department: 'الدعم الفني والعمليات',
    avatar: 'س',
    password: '123',
    permissions: getDefaultPermissionsForRole('Agent'),
  },
];

export const INITIAL_CATEGORIES: CategoryRule[] = [
  {
    id: 'cat-1',
    name: 'تقني / Technical',
    assignedTeam: 'فريق الدعم البرمجي',
    defaultOwner: 'محمد علي',
    description: 'معالجة الأخطاء البرمجية، تكامل واجهات API، والمشاكل التقنية في الأنظمة.',
    color: 'indigo',
    active: true,
    routingStrategy: 'direct',
    keywords: ['خطأ', 'API', 'Bug', 'كود', 'برمجة', 'قاعدة بيانات'],
    escalationEmail: 'tech-escalation@company.com',
    businessHoursOnly: false,
    slaHours: { Critical: 3, High: 8, Medium: 24, Low: 48 },
  },
  {
    id: 'cat-2',
    name: 'بنية تحتية وشبكات / Infrastructure',
    assignedTeam: 'فريق الشبكات والسيرفرات',
    defaultOwner: 'عمر اليافعي',
    description: 'متابعة السيرفرات السحابية، أمان الشبكات، التخزين ومراكز البيانات.',
    color: 'cyan',
    active: true,
    routingStrategy: 'least_busy',
    keywords: ['سيرفر', 'شبكة', 'Cloud', 'استضافة', 'بطء', 'VPN', 'انقطاع'],
    escalationEmail: 'devops-lead@company.com',
    businessHoursOnly: false,
    slaHours: { Critical: 2, High: 6, Medium: 12, Low: 36 },
  },
  {
    id: 'cat-3',
    name: 'مالي واشتراكات / Financial',
    assignedTeam: 'الإدارة المالية',
    defaultOwner: 'أحمد العتيبي',
    description: 'عمليات الدفع، الفواتير الضريبية، الاشتراكات والتحويلات البنكية.',
    color: 'amber',
    active: true,
    routingStrategy: 'direct',
    keywords: ['فاتورة', 'دفع', 'سداد', 'اشتراك', 'ضريبة', 'تحويل', 'استرجاع'],
    escalationEmail: 'finance-alerts@company.com',
    businessHoursOnly: true,
    slaHours: { Critical: 4, High: 12, Medium: 24, Low: 48 },
  },
  {
    id: 'cat-4',
    name: 'خدمة عملاء / Customer Service',
    assignedTeam: 'فريق تجربة العميل',
    defaultOwner: 'سارة خالد',
    description: 'الاستفسارات العامة، متابعة شكاوى العملاء، وتحديث بيانات الحسابات.',
    color: 'emerald',
    active: true,
    routingStrategy: 'round_robin',
    keywords: ['استفسار', 'شكوى', 'عميل', 'حساب', 'تحديث', 'دعم'],
    escalationEmail: 'cs-manager@company.com',
    businessHoursOnly: true,
    slaHours: { Critical: 4, High: 10, Medium: 20, Low: 48 },
  },
];

export const INITIAL_TAGS: string[] = [
  'VIP Client',
  'Hardware',
  'Software Bug',
  'Database',
  'Payment Gateway',
  'Cloud Server',
  'Security & Auth',
  'UI/UX Issue',
];

export const INITIAL_CANNED_RESPONSES: string[] = [
  'تمت المعالجة الفنية وإعادة الخدمة للعمل بكفاءة 100%.',
  'تم إصلاح الخلل البرمجي وإجراء اختبار شامل للوظيفة مع العميل.',
  'المشكلة ناتجة عن خطأ في مدخلات المستخدم، تم تصحيح البيانات والتواصل معه.',
  'تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
  'تم التحقق من استقرار السيرفر وعودة استجابة الـ API للمعدل الطبيعي.',
];

export const INITIAL_SOUND_SETTINGS: SoundSettings = {
  muted: false,
  alarmUrl: 'https://assets.mixkit.co/active_storage/sfx/995/995-preview.mp3',
  alarmStyle: 'pulse-red',
  volume: 0.8,
};

export const INITIAL_ISSUES: Issue[] = [];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'a-1',
    time: new Date().toLocaleTimeString('ar-EG', { hour: '2-digit', minute: '2-digit' }),
    user: 'أحمد العتيبي (مدير النظام)',
    action: 'تهيئة النظام المتطور',
    details: 'تم تشغيل النسخة المؤسسية المحسنة مع تصحيح عداد الوقت ومنظومة SLA الدقيقة.',
  },
  {
    id: 'a-2',
    time: 'منذ 3 ساعات',
    user: 'محمد علي',
    action: 'تحديث حالة تذكرة',
    details: 'بدء العمل على تذكرة بوابة الدفع INC-1001 وتفعيل التتبع الزمني.',
  },
];

export const INITIAL_GENERAL_SETTINGS: GeneralSettings = {
  appName: 'منظومة تتبع وإدارة المشاكل',
  appBadge: 'Enterprise Pro',
  appSubtitle: 'SLA Watcher • CSAT Metrics • Accurate Work Timer & Activity Trail',
  companyName: 'منظومة الدعم والعمليات الذكية',
  copyrightText: 'جميع الحقوق محفوظة © ' + new Date().getFullYear(),
  appLogoIcon: 'Headset',
  headerColorPreset: 'indigo-emerald',
  showBadge: true,
  showSubtitle: true,
  showFooterCopyright: true,
  customFooterNote: 'نظام إدارة البلاغات والتذاكر المؤسسي الموحد',
  badgeStyle: 'clean-arabic',
  cabDesignStyle: 'dynamic_table',
  lightThemeBgColor: 'default',
  lightCardBgColor: 'default',
  lightHeaderBgColor: 'default',
  customLightBgHex: '#f8fafc',
  customCardBgHex: '#ffffff',
  customHeaderBgHex: '#ffffff',
};

export const INITIAL_CAB_ACTIVITIES: CabBusinessActivity[] = [
  {
    id: 'CAB-2026-001',
    activityName: 'Core Database Migration & Engine Patch',
    scope: 'Upgrading primary PostgreSQL cluster to v16 with security patches and indexes optimization.',
    impactedServices: 'Payment Gateway, User Authentication API, Client Portal',
    serviceImpact: 'Brief intermittent latency during master node failover switch',
    stopServiceTargetSystem: 'خادم قاعدة البيانات الرئيسي (Primary DB Cluster - Node 01)',
    stoppedSystemName: 'نظام المعاملات الدفع والتوثيق (Payment & Auth Services)',
    downtimeRequired: 'Yes',
    date: 'Sunday, 28/09/2026',
    startTime: '02:00 AM',
    endTime: '04:00 AM',
    maintenanceWindow: '02:00 AM - 04:00 AM',
    requestor: 'أحمد العتيبي',
    tpm: 'عمر اليافعي',
    changeManagement: 'IT Change Management Team',
    status: 'Approved',
    riskLevel: 'High',
    rollbackPlan: 'Restore snapshot from automated WAL archives and switch traffic back to replica cluster v15 within 10 minutes.',
    comments: [
      {
        id: 'cb-1',
        author: 'أحمد العتيبي',
        content: 'تم اختبار الخطة على بيئة Staging والتأكد من توافق الجداول.',
        createdAt: '2026-09-27 10:30',
        type: 'general',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'CAB-2026-002',
    activityName: 'Edge Router & Firewall Firmware Update',
    scope: 'Applying zero-day vulnerability security patch on secondary core switch in HQ Data Center.',
    impactedServices: 'Internal Corporate VPN, Local Network Shared Drives',
    serviceImpact: 'No impact expected due to redundant HA traffic routing',
    stopServiceTargetSystem: 'محبس الاتصال الشبكي الفرعي (Secondary Edge Router)',
    stoppedSystemName: 'شبكة الـ VPN الداخلية للموظفين (Corporate VPN Network)',
    downtimeRequired: 'No',
    date: 'Tuesday, 30/09/2026',
    startTime: '11:00 PM',
    endTime: '11:45 PM',
    maintenanceWindow: '11:00 PM - 11:45 PM',
    requestor: 'سارة خالد',
    tpm: 'محمد علي',
    changeManagement: 'IT Change Management Team',
    status: 'Pending Approval',
    riskLevel: 'Medium',
    rollbackPlan: 'Revert switch firmware to dual-boot secondary image via console CLI.',
    comments: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'CAB-2026-003',
    activityName: 'Payment Gateway API SSL Certificate Renewal',
    scope: 'Replacing expiring wildcard SSL/TLS certificate for payment endpoints.',
    impactedServices: 'Payment Gateway, Merchant Portal',
    serviceImpact: 'No downtime, seamless certificate hot-reload.',
    stopServiceTargetSystem: 'خادم شهادات التشفير (SSL Reverse Proxy)',
    stoppedSystemName: 'بوابة خوادم التجار والـ APIs (Merchant Gateway API)',
    downtimeRequired: 'No',
    date: 'Sunday, 28/09/2026',
    startTime: '03:00 AM',
    endTime: '03:30 AM',
    maintenanceWindow: '03:00 AM - 03:30 AM',
    requestor: 'محمد علي',
    tpm: 'أحمد العتيبي',
    changeManagement: 'IT Change Management Team',
    status: 'Pending Approval',
    riskLevel: 'Low',
    rollbackPlan: 'Reload previous SSL certificate bundle in Nginx key store.',
    comments: [],
    createdAt: new Date().toISOString(),
  },
];

