import { Issue, AppUser, CategoryRule, AuditLog, SoundSettings, GeneralSettings, CabBusinessActivity } from '../types';
import { calculateDueDate } from './sla';
import { getDefaultPermissionsForRole } from './permissions';

export const INITIAL_USERS: AppUser[] = [
  {
    id: 'usr-1',
    name: 'أحمد العتيبي',
    username: 'admin',
    email: 'admin@company.com',
    role: 'Admin',
    department: 'الإدارة العليا / IT Operations',
    avatar: 'أ',
    password: 'admin',
    permissions: getDefaultPermissionsForRole('Admin'),
  },
  {
    id: 'usr-2',
    name: 'محمد علي',
    username: 'agent1',
    email: 'agent1@company.com',
    role: 'Agent',
    department: 'فريق الدعم البرمجي',
    avatar: 'م',
    password: '123',
    permissions: getDefaultPermissionsForRole('Agent'),
  },
  {
    id: 'usr-3',
    name: 'سارة خالد',
    username: 'agent2',
    email: 'sara@company.com',
    role: 'Supervisor',
    department: 'خدمة العملاء واللوجستيات',
    avatar: 'س',
    password: '123',
    permissions: getDefaultPermissionsForRole('Supervisor'),
  },
  {
    id: 'usr-4',
    name: 'عمر اليافعي',
    username: 'agent3',
    email: 'omar@company.com',
    role: 'Agent',
    department: 'البنية التحتية والشبكات',
    avatar: 'ع',
    password: '123',
    permissions: getDefaultPermissionsForRole('Agent'),
  },
  {
    id: 'usr-1790256968066',
    name: 'محمد رمضان',
    username: 'محمد.رمضان',
    email: 'محمد.رمضان@support.internal',
    role: 'Supervisor',
    department: 'بيب',
    avatar: 'م',
    password: '123',
    permissions: getDefaultPermissionsForRole('Supervisor'),
  },
  {
    id: 'usr-1790553494732',
    name: 'سسب',
    username: 'يسي',
    email: 'jsf@gmail.com',
    role: 'Agent',
    department: 'الدعم الفني والعمليات',
    avatar: 'س',
    password: '123',
    permissions: getDefaultPermissionsForRole('Agent'),
  },
];

export const INITIAL_CATEGORIES: CategoryRule[] = [
  {
    id: 'cat-1',
    name: 'تقني / Technical',
    assignedTeam: 'فريق الدعم البرمجي',
    defaultOwner: 'محمد علي',
    description: 'معالجة الأخطاء البرمجية، تكامل واجهات API، والمشاكل التقنية في الأنظمة.',
    color: 'indigo',
    active: true,
    routingStrategy: 'direct',
    keywords: ['خطأ', 'API', 'Bug', 'كود', 'برمجة', 'قاعدة بيانات'],
    escalationEmail: 'tech-escalation@company.com',
    businessHoursOnly: false,
    slaHours: { Critical: 3, High: 8, Medium: 24, Low: 48 },
  },
  {
    id: 'cat-2',
    name: 'بنية تحتية وشبكات / Infrastructure',
    assignedTeam: 'فريق الشبكات والسيرفرات',
    defaultOwner: 'عمر اليافعي',
    description: 'متابعة السيرفرات السحابية، أمان الشبكات، التخزين ومراكز البيانات.',
    color: 'cyan',
    active: true,
    routingStrategy: 'least_busy',
    keywords: ['سيرفر', 'شبكة', 'Cloud', 'استضافة', 'بطء', 'VPN', 'انقطاع'],
    escalationEmail: 'devops-lead@company.com',
    businessHoursOnly: false,
    slaHours: { Critical: 2, High: 6, Medium: 12, Low: 36 },
  },
  {
    id: 'cat-3',
    name: 'مالي واشتراكات / Financial',
    assignedTeam: 'الإدارة المالية',
    defaultOwner: 'أحمد العتيبي',
    description: 'عمليات الدفع، الفواتير الضريبية، الاشتراكات والتحويلات البنكية.',
    color: 'amber',
    active: true,
    routingStrategy: 'direct',
    keywords: ['فاتورة', 'دفع', 'سداد', 'اشتراك', 'ضريبة', 'تحويل', 'استرجاع'],
    escalationEmail: 'finance-alerts@company.com',
    businessHoursOnly: true,
    slaHours: { Critical: 4, High: 12, Medium: 24, Low: 48 },
  },
  {
    id: 'cat-4',
    name: 'خدمة عملاء / Customer Service',
    assignedTeam: 'فريق تجربة العميل',
    defaultOwner: 'سارة خالد',
    description: 'الاستفسارات العامة، متابعة شكاوى العملاء، وتحديث بيانات الحسابات.',
    color: 'emerald',
    active: true,
    routingStrategy: 'round_robin',
    keywords: ['استفسار', 'شكوى', 'عميل', 'حساب', 'تحديث', 'دعم'],
    escalationEmail: 'cs-manager@company.com',
    businessHoursOnly: true,
    slaHours: { Critical: 4, High: 10, Medium: 20, Low: 48 },
  },
];

export const INITIAL_TAGS: string[] = [
  'VIP Client',
  'Hardware',
  'Software Bug',
  'Database',
  'Payment Gateway',
  'Cloud Server',
  'Security & Auth',
  'UI/UX Issue',
];

export const INITIAL_CANNED_RESPONSES: string[] = [
  'تمت المعالجة الفنية وإعادة الخدمة للعمل بكفاءة 100%.',
  'تم إصلاح الخلل البرمجي وإجراء اختبار شامل للوظيفة مع العميل.',
  'المشكلة ناتجة عن خطأ في مدخلات المستخدم، تم تصحيح البيانات والتواصل معه.',
  'تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
  'تم التحقق من استقرار السيرفر وعودة استجابة الـ API للمعدل الطبيعي.',
];

export const INITIAL_SOUND_SETTINGS: SoundSettings = {
  muted: false,
  alarmUrl: 'https://assets.mixkit.co/active_storage/sfx/995/995-preview.mp3',
  alarmStyle: 'pulse-red',
  volume: 0.8,
};

export const INITIAL_ISSUES: Issue[] = [
  {
    id: 'INC-1006',
    client: 'سيس للخدمات التقنية',
    clientEmail: 'mohamec@gmail.com',
    clientPhone: '+966 55 987 6543',
    tag: 'Database',
    type: 'تقني / Technical',
    desc: 'مشكلة في مزامنة البيانات عبر السحابة اللحظية وتحديث سجلات التذاكر',
    assigned: 'فريق الدعم البرمجي',
    owner: 'محمد علي',
    priority: 'High',
    status: 'Open',
    createdAt: '2026-09-26T10:00:00.000Z',
    dueDate: '2026-09-27T10:00:00.000Z',
    workTime: 0,
    isWorkingNow: false,
    activeWorker: null,
    csat: 5,
    comments: [
      {
        id: 'c-1790359041889',
        user: 'أحمد العتيبي',
        text: 'تذكرة مفتوحة ومسجلة في السحابة المركزية، جاهزة للبدء والمتابعة من أي جهاز.',
        time: 'الآن',
      },
    ],
    timeline: [
      {
        id: 't-1790359041889',
        time: 'الآن',
        actor: 'محمد علي',
        title: 'تسجيل التذكرة في السحابة 🌐',
        details: 'تم فتح التذكرة ومزامنتها سحابياً لجميع أعضاء الفريق.',
        type: 'create',
      },
    ],
  },
  {
    id: 'INC-1005',
    client: 'يبي',
    clientEmail: 'mo@gmail',
    clientPhone: 'بيب',
    tag: 'Database',
    type: 'تقني / Technical',
    desc: 'ss',
    assigned: 'فريق الدعم البرمجي',
    owner: 'محمد علي',
    priority: 'Low',
    status: 'Resolved',
    createdAt: '2026-09-22T22:07:26.254Z',
    dueDate: '2026-09-24T22:07:26.254Z',
    workTime: 76,
    isWorkingNow: false,
    activeWorker: null,
    csat: 5,
    comments: [
      {
        id: 'c-1790115235006',
        user: 'أحمد العتيبي',
        text: '🔒 تم حل وإغلاق التذكرة. الإجراء المعتمد: تمت المعالجة الفنية وإعادة الخدمة للعمل بكفاءة 100%.',
        time: 'الآن',
      },
    ],
    timeline: [
      {
        id: 't-1790115235006',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'حل وإغلاق البلاغ 🟢',
        details: 'تم حل المشكلة واعتماد الإجراء: تمت المعالجة الفنية وإعادة الخدمة للعمل بكفاءة 100%.',
        type: 'resolve',
      },
      {
        id: 't-1790114945838',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'إيقاف مؤقت للعداد',
        details: 'تم إيقاف مؤقت العمل عند 76 ثانية.',
        type: 'timer',
      },
      {
        id: 't-1790114868310',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'بدء جلسة العمل',
        details: 'بدأ الموظف أحمد العتيبي العمل على التذكرة وتشغيل المؤقت.',
        type: 'timer',
      },
      {
        id: 't-1790114846254',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'إنشاء التذكرة',
        details: 'تم تسجيل البلاغ وإسناده إلى محمد علي بحالة Open.',
        type: 'create',
      },
    ],
    resolutionReason: 'تمت المعالجة الفنية وإعادة الخدمة للعمل بكفاءة 100%.',
    resolvedAt: '2026-09-22T22:13:55.006Z',
  },
  {
    id: 'INC-1001',
    client: 'شركة الأمل الدولية للتقنية',
    clientEmail: 'contact@alamal-tech.com',
    clientPhone: '+966 50 123 4567',
    tag: 'VIP Client',
    type: 'تقني / Technical',
    desc: 'توقف مفاجئ في بوابة الدفع الإلكتروني عند محاولة المستخدمين سداد الفواتير الشهرية وظهور خطأ 502 Bad Gateway.',
    assigned: 'فريق الدعم البرمجي',
    owner: 'محمد علي',
    priority: 'Critical',
    status: 'Resolved',
    createdAt: '2026-09-22T17:44:33.422Z',
    dueDate: '2026-09-22T20:44:33.422Z',
    workTime: 3840,
    isWorkingNow: false,
    activeWorker: null,
    csat: 5,
    comments: [
      {
        id: 'c-1',
        user: 'محمد علي',
        text: 'تم فحص سجلات Nginx وتبيّن وجود ضغط مفاجئ على microservice السداد. جاري إعادة تشغيل الحاوية وتوسيع الذاكرة.',
        time: 'منذ ساعتين',
      },
      {
        id: 'c-1790115238941',
        user: 'أحمد العتيبي',
        text: '🔒 تم حل وإغلاق التذكرة. الإجراء المعتمد: تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
        time: 'الآن',
      },
    ],
    timeline: [
      {
        id: 't-1790115238941',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'حل وإغلاق البلاغ 🟢',
        details: 'تم حل المشكلة واعتماد الإجراء: تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
        type: 'resolve',
      },
      {
        id: 't-1790114476717',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'إيقاف مؤقت للعداد',
        details: 'تم إيقاف مؤقت العمل عند 3841 ثانية.',
        type: 'timer',
      },
      {
        id: 't-1790114475107',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'بدء جلسة العمل',
        details: 'بدأ الموظف أحمد العتيبي العمل على التذكرة وتشغيل المؤقت.',
        type: 'timer',
      },
      {
        id: 't-1',
        time: 'منذ 4 ساعات',
        actor: 'النظام',
        title: 'إنشاء التذكرة',
        details: 'تم استلام البلاغ برقم INC-1001 وتعيينه تلقائياً لمحمد علي بالأولوية الحرج.',
        type: 'create',
      },
    ],
    resolutionReason: 'تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
    resolvedAt: '2026-09-22T22:13:58.941Z',
  },
  {
    id: 'INC-1002',
    client: 'مستشفى السلام التخصصي',
    clientEmail: 'support@alsalam-med.org',
    clientPhone: '+966 55 987 6543',
    tag: 'Cloud Server',
    type: 'بنية تحتية وشبكات / Infrastructure',
    desc: 'بطء ملحوظ في استرجاع سجلات المرضى على قاعدة بيانات السحابة خلال فترة الذروة الصباحية.',
    assigned: 'فريق الشبكات والسيرفرات',
    owner: 'عمر اليافعي',
    priority: 'High',
    status: 'Resolved',
    createdAt: '2026-09-22T21:14:33.422Z',
    dueDate: '2026-09-23T03:14:33.422Z',
    workTime: 1200,
    isWorkingNow: false,
    activeWorker: null,
    csat: 4,
    comments: [
      {
        id: 'c-2',
        user: 'عمر اليافعي',
        text: 'تم ملاحظة CPU spike بنسبة 94% بسبب استعلام إحصائي غير مفهرس على جدول المواعيد.',
        time: 'منذ 15 دقيقة',
      },
      {
        id: 'c-1790115253740',
        user: 'أحمد العتيبي',
        text: '🔒 تم حل وإغلاق التذكرة. الإجراء المعتمد: تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
        time: 'الآن',
      },
    ],
    timeline: [
      {
        id: 't-1790115253740',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'حل وإغلاق البلاغ 🟢',
        details: 'تم حل المشكلة واعتماد الإجراء: تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
        type: 'resolve',
      },
      {
        id: 't-4',
        time: 'منذ 30 دقيقة',
        actor: 'النظام',
        title: 'إنشاء التذكرة',
        details: 'تسجيل بلاغ بطء السيرفرات وإسنادها إلى عمر اليافعي.',
        type: 'create',
      },
    ],
    resolutionReason: 'تم تحويل الطلب للفريق الهندسي المختص وتحديث الصلاحيات بنجاح.',
    resolvedAt: '2026-09-22T22:14:13.740Z',
  },
  {
    id: 'INC-1003',
    client: 'مجموعة الميرا للحلول اللوجستية',
    clientEmail: 'ops@almeera-logistics.sa',
    tag: 'Payment Gateway',
    type: 'مالي واشتراكات / Financial',
    desc: 'طلب تعديل الدورة الفوترية وترقية باقة الاشتراك السنوية مع إضافة 15 مستخدماً إضافياً.',
    assigned: 'الإدارة المالية',
    owner: 'أحمد العتيبي',
    priority: 'Medium',
    status: 'Resolved',
    createdAt: '2026-09-20T21:44:33.422Z',
    dueDate: '2026-09-21T21:44:33.422Z',
    workTime: 5400,
    resolutionReason: 'تم إصدار الفاتورة المحدثة وتفعيل التراخيص الإضافية للعميل مع اعتماد الخصم السنوي.',
    resolvedAt: '2026-09-21T20:44:33.422Z',
    csat: 5,
    comments: [
      {
        id: 'c-3',
        user: 'أحمد العتيبي',
        text: 'تم تجهيز عرض السعر المعدل وإرساله للمدير المالي لاعتماده.',
        time: 'أمس الساعة 11:00 ص',
      },
      {
        id: 'c-4',
        user: 'النظام',
        text: '🔒 تم إغلاق وحل التذكرة بنجاح من قبل أحمد العتيبي.',
        time: 'أمس الساعة 03:30 م',
      },
    ],
    timeline: [
      {
        id: 't-5',
        time: 'منذ يومين',
        actor: 'النظام',
        title: 'إنشاء التذكرة',
        details: 'تم استلام طلب ترقية الحساب.',
        type: 'create',
      },
      {
        id: 't-6',
        time: 'منذ يوم',
        actor: 'أحمد العتيبي',
        title: 'حل وإغلاق المشكلة',
        details: 'تم إصدار الفاتورة المحدثة وتفعيل التراخيص بنجاح.',
        type: 'resolve',
      },
    ],
  },
  {
    id: 'INC-1004',
    client: 'منصة تداول العقارات الذكية',
    clientEmail: 'info@aqar-smart.com',
    tag: 'Software Bug',
    type: 'خدمة عملاء / Customer Service',
    desc: 'عدم وصول رسائل التفعيل OTP لبعض المشتركين الجدد عبر مزود خدمة الرسائل القصيرة.',
    assigned: 'فريق تجربة العميل',
    owner: 'سارة خالد',
    priority: 'High',
    status: 'Resolved',
    createdAt: '2026-09-21T20:44:33.422Z',
    dueDate: '2026-09-22T06:44:33.422Z',
    workTime: 2300,
    csat: 3,
    comments: [
      {
        id: 'c-5',
        user: 'سارة خالد',
        text: 'تم فتح تذكرة مع مزود بوابة الـ SMS وبانتظار رد المهندس المسؤول حول حظر بعض النطاقات.',
        time: 'منذ 18 ساعة',
      },
      {
        id: 'c-1790115259379',
        user: 'أحمد العتيبي',
        text: '🔒 تم حل وإغلاق التذكرة. الإجراء المعتمد: المشكلة ناتجة عن خطأ في مدخلات المستخدم، تم تصحيح البيانات والتواصل معه.',
        time: 'الآن',
      },
    ],
    timeline: [
      {
        id: 't-1790115259379',
        time: 'الآن',
        actor: 'أحمد العتيبي',
        title: 'حل وإغلاق البلاغ 🟢',
        details: 'تم حل المشكلة واعتماد الإجراء: المشكلة ناتجة عن خطأ في مدخلات المستخدم، تم تصحيح البيانات والتواصل معه.',
        type: 'resolve',
      },
      {
        id: 't-7',
        time: 'منذ 25 ساعة',
        actor: 'النظام',
        title: 'إنشاء التذكرة',
        details: 'تسجيل بلاغ رسائل الـ SMS.',
        type: 'create',
      },
      {
        id: 't-8',
        time: 'منذ 20 ساعة',
        actor: 'سارة خالد',
        title: 'تعليق التذكرة (Pending)',
        details: 'التذكرة معلقة بانتظار رد مزود بوابة الرسائل.',
        type: 'status',
      },
      {
        id: 't-9',
        time: 'منذ 15 ساعة',
        actor: 'SLA Guard',
        title: 'تجاوز الـ SLA ⚠️',
        details: 'تجاوزت التذكرة 10 ساعات في حالة المعلقة.',
        type: 'sla',
      },
    ],
    resolutionReason: 'المشكلة ناتجة عن خطأ في مدخلات المستخدم، تم تصحيح البيانات والتواصل معه.',
    resolvedAt: '2026-09-22T22:14:19.379Z',
    isWorkingNow: false,
    activeWorker: null,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'a-1',
    time: new Date().toLocaleTimeString('ar-EG', { hour: '2-digit', minute: '2-digit' }),
    user: 'أحمد العتيبي (مدير النظام)',
    action: 'تهيئة النظام المتطور',
    details: 'تم تشغيل النسخة المؤسسية المحسنة مع تصحيح عداد الوقت ومنظومة SLA الدقيقة.',
  },
  {
    id: 'a-2',
    time: 'منذ 3 ساعات',
    user: 'محمد علي',
    action: 'تحديث حالة تذكرة',
    details: 'بدء العمل على تذكرة بوابة الدفع INC-1001 وتفعيل التتبع الزمني.',
  },
];

export const INITIAL_GENERAL_SETTINGS: GeneralSettings = {
  appName: 'منظومة تتبع وإدارة المشاكل',
  appBadge: 'Enterprise Pro',
  appSubtitle: 'SLA Watcher • CSAT Metrics • Accurate Work Timer & Activity Trail',
  companyName: 'منظومة الدعم والعمليات الذكية',
  copyrightText: 'جميع الحقوق محفوظة © ' + new Date().getFullYear(),
  appLogoIcon: 'Headset',
  headerColorPreset: 'indigo-emerald',
  showBadge: true,
  showSubtitle: true,
  showFooterCopyright: true,
  customFooterNote: 'نظام إدارة البلاغات والتذاكر المؤسسي الموحد',
  badgeStyle: 'clean-arabic',
  cabDesignStyle: 'dynamic_table',
  lightThemeBgColor: 'default',
  lightCardBgColor: 'default',
  lightHeaderBgColor: 'default',
  customLightBgHex: '#f8fafc',
  customCardBgHex: '#ffffff',
  customHeaderBgHex: '#ffffff',
};

export const INITIAL_CAB_ACTIVITIES: CabBusinessActivity[] = [
  {
    id: 'CAB-2026-001',
    activityName: 'Core Database Migration & Engine Patch',
    scope: 'Upgrading primary PostgreSQL cluster to v16 with security patches and indexes optimization.',
    impactedServices: 'Payment Gateway, User Authentication API, Client Portal',
    serviceImpact: 'Brief intermittent latency during master node failover switch',
    stopServiceTargetSystem: 'خادم قاعدة البيانات الرئيسي (Primary DB Cluster - Node 01)',
    stoppedSystemName: 'نظام المعاملات الدفع والتوثيق (Payment & Auth Services)',
    downtimeRequired: 'Yes',
    date: 'Sunday, 28/09/2026',
    startTime: '02:00 AM',
    endTime: '04:00 AM',
    maintenanceWindow: '02:00 AM - 04:00 AM',
    requestor: 'أحمد العتيبي',
    tpm: 'عمر اليافعي',
    changeManagement: 'IT Change Management Team',
    status: 'Approved',
    riskLevel: 'High',
    rollbackPlan: 'Restore snapshot from automated WAL archives and switch traffic back to replica cluster v15 within 10 minutes.',
    comments: [
      {
        id: 'cb-1',
        author: 'أحمد العتيبي',
        content: 'تم اختبار الخطة على بيئة Staging والتأكد من توافق الجداول.',
        createdAt: '2026-09-27 10:30',
        type: 'general',
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'CAB-2026-002',
    activityName: 'Edge Router & Firewall Firmware Update',
    scope: 'Applying zero-day vulnerability security patch on secondary core switch in HQ Data Center.',
    impactedServices: 'Internal Corporate VPN, Local Network Shared Drives',
    serviceImpact: 'No impact expected due to redundant HA traffic routing',
    stopServiceTargetSystem: 'محبس الاتصال الشبكي الفرعي (Secondary Edge Router)',
    stoppedSystemName: 'شبكة الـ VPN الداخلية للموظفين (Corporate VPN Network)',
    downtimeRequired: 'No',
    date: 'Tuesday, 30/09/2026',
    startTime: '11:00 PM',
    endTime: '11:45 PM',
    maintenanceWindow: '11:00 PM - 11:45 PM',
    requestor: 'سارة خالد',
    tpm: 'محمد علي',
    changeManagement: 'IT Change Management Team',
    status: 'Pending Approval',
    riskLevel: 'Medium',
    rollbackPlan: 'Revert switch firmware to dual-boot secondary image via console CLI.',
    comments: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'CAB-2026-003',
    activityName: 'Payment Gateway API SSL Certificate Renewal',
    scope: 'Replacing expiring wildcard SSL/TLS certificate for payment endpoints.',
    impactedServices: 'Payment Gateway, Merchant Portal',
    serviceImpact: 'No downtime, seamless certificate hot-reload.',
    stopServiceTargetSystem: 'خادم شهادات التشفير (SSL Reverse Proxy)',
    stoppedSystemName: 'بوابة خوادم التجار والـ APIs (Merchant Gateway API)',
    downtimeRequired: 'No',
    date: 'Sunday, 28/09/2026',
    startTime: '03:00 AM',
    endTime: '03:30 AM',
    maintenanceWindow: '03:00 AM - 03:30 AM',
    requestor: 'محمد علي',
    tpm: 'أحمد العتيبي',
    changeManagement: 'IT Change Management Team',
    status: 'Pending Approval',
    riskLevel: 'Low',
    rollbackPlan: 'Reload previous SSL certificate bundle in Nginx key store.',
    comments: [],
    createdAt: new Date().toISOString(),
  },
];

